env:
  global:
    - CC_TEST_REPORTER_ID=bf9c03f607a79462da38c8f3dafaaca7c62e88c938aabb82e0555ebb4d4a6b0d
language: ruby
rvm:
  - 2.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate 
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT