development:
  adapter: postgresql
  encoding: unicode
  database: music-search_development
  pool: 5
  username: erikperez
  password: postgresql

test:
  adapter: postgresql
  encoding: unicode
  database: music-search
  pool: 5
  username: erikperez
  password: postgresql


production:
  adapter: postgresql
  encoding: unicode
  database: music-search_production
  pool: 5
  username: erikperez
  password: postgresql
