development:
  adapter: postgresql
  encoding: unicode
  database: music-search_development
  pool: 5
  username: postgres
  password: postgresql

test:
  adapter: postgresql
  encoding: unicode
  database: music-search
  pool: 5
  username: postgres
  password: postgresql


production:
  adapter: postgresql
  encoding: unicode
  database: music-search_production
  pool: 5
  username: postgres
  password: postgresql

production:
adapter: postgresql
encoding: unicode
pool: 5
database: <%= ENV['DATABASE_URL'] %>
username: <%= ENV['DATABASE_USERNAME'] %>
password: <%= ENV['DATABASE_PASSWORD'] %>
